# Generated by Django 4.2.2 on 2023-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('mail', models.CharField(default='', max_length=40)),
                ('inbox', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
