# Generated by Django 4.2.2 on 2023-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_restore'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('mail', models.EmailField(default='', max_length=40)),
                ('inbox', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
